# Generated by Django 4.2.23 on 2025-07-25 06:51

import django.contrib.postgres.fields
from django.db import migrations, models
import pgvector.django.vector


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('url', models.URLField(db_index=True, max_length=500, unique=True)),
                ('source_name', models.CharField(db_index=True, max_length=100)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, db_index=True, dimensions=1536, null=True)),
                ('is_processed_for_embedding', models.BooleanField(db_index=True, default=False)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None, verbose_name='Identified Keywords')),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None, verbose_name='Identified Categories')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('url', models.URLField(db_index=True, max_length=2048, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'News Source',
                'verbose_name_plural': 'News Sources',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='news_source_name_idx'), models.Index(fields=['url'], name='news_source_url_idx')],
            },
        ),
    ]
