# Generated by Django 4.2.23 on 2025-07-29 05:27

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, db_index=True, dimensions=768, null=True),
        ),
    ]
