# Generated by Django 4.2.23 on 2025-07-29 05:35

from django.db import migrations, models
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsarticle_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='is_processed_for_embedding',
            field=models.BooleanField(default=False),
        ),
    ]
