# Generated by Django 5.2 on 2025-04-20 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_level', models.IntegerField(default=0, null=True, verbose_name='关注级别')),
                ('position_shares', models.DecimalField(decimal_places=4, default=0, max_digits=18, null=True, verbose_name='持仓股数')),
                ('average_cost_price', models.DecimalField(decimal_places=4, default=0, max_digits=18, null=True, verbose_name='持仓均价')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('alert_settings', models.JSONField(blank=True, default=dict, help_text='{"price": "alert"}', null=True, verbose_name='预警设置')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='stocks.stock', verbose_name='股票')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '自选股票',
                'verbose_name_plural': '股票关注列表',
                'ordering': ['-added_at'],
                'unique_together': {('user', 'stock')},
            },
        ),
    ]
