# Generated by Django 5.2 on 2025-04-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0001_initial'),
        ('users', '0001_initial'),
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watched_stocks',
            field=models.ManyToManyField(blank=True, related_name='watchers', through='watchlist.Watchlist', through_fields=('user', 'stock'), to='stocks.stock', verbose_name='Watched Stocks'),
        ),
    ]
