# Generated by Django 4.2.23 on 2025-07-25 06:51

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the user profile', primary_key=True, serialize=False, verbose_name='Profile ID')),
                ('user_self_portrait', models.TextField(blank=True, help_text='A brief self-description or portrait of the user', null=True, verbose_name='Self Portrait')),
                ('preferred_topic', models.JSONField(blank=True, default=list, help_text='List of topics the user is interested in', verbose_name='Preferred Topics')),
                ('excluded_topic', models.JSONField(blank=True, default=list, help_text='List of topics the user is not interested in', verbose_name='Excluded Topics')),
                ('interest_embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text="Embedding vector representing the user's interests", null=True, size=None, verbose_name='Interest Embedding')),
                ('is_processed_for_embedding', models.BooleanField(db_index=True, default=False, help_text='Flag indicating if the user profile has been processed for embedding', verbose_name='Processed for Embedding')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update to the user profile', verbose_name='Last Updated')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['user__username'],
                'indexes': [models.Index(fields=['user'], name='user_profile_user_idx'), models.Index(fields=['is_processed_for_embedding'], name='user_profile_processed_idx')],
            },
        ),
    ]
