# Generated by Django 4.2.23 on 2025-07-28 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_options_userprofile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the user profile was created', verbose_name='Created At'),
        ),
    ]
