# Generated by Django 4.2.23 on 2025-07-29 05:27

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='interest_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, help_text="Embedding vector representing the user's interests", null=True, verbose_name='Interest Embedding'),
        ),
    ]
