# Generated by Django 5.2 on 2025-04-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_symbol', models.CharField(db_index=True, max_length=20, verbose_name='股票代码')),
                ('exchange', models.CharField(db_index=True, max_length=50, verbose_name='交易所')),
                ('company_name', models.CharField(max_length=100, verbose_name='公司名称')),
                ('isin', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='国际证券识别码')),
                ('sector', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='行业')),
                ('industry', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='子行业')),
                ('logo_url', models.URLField(blank=True, max_length=512, null=True, verbose_name='公司logo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='公司简介')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='国家')),
                ('currency', models.CharField(blank=True, max_length=10, null=True, verbose_name='货币')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '股票',
                'verbose_name_plural': '股票集',
                'ordering': ['ticker_symbol'],
                'indexes': [models.Index(fields=['ticker_symbol', 'exchange'], name='ticker_symbol_exchange_idx')],
                'unique_together': {('ticker_symbol', 'exchange')},
            },
        ),
    ]
