# Generated by Django 4.2.23 on 2025-07-25 09:16

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsBriefingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Report Generated At')),
                ('report_date', models.DateField(db_index=True)),
                ('news_articles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, size=None, verbose_name='News Articles')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Report Summary')),
                ('full_report_content', models.TextField(blank=True, null=True, verbose_name='Full Report Content')),
                ('key_directions', models.JSONField(blank=True, null=True, verbose_name='Key Directions')),
                ('recommendation_score', models.IntegerField(default=0, verbose_name='Recommendation Score')),
                ('related_stocks', models.JSONField(blank=True, null=True, verbose_name='Related Stocks')),
                ('ai_impact_score', models.TextField(blank=True, null=True, verbose_name='AI Impact Score')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_briefing_reports', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'News Briefing Report',
                'verbose_name_plural': 'News Briefing Reports',
                'ordering': ['-report_date'],
            },
        ),
    ]
