# Generated by Django 5.2 on 2025-04-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('url', models.URLField(db_index=True, max_length=500, unique=True)),
                ('source_name', models.CharField(db_index=True, max_length=100)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
