# Generated by Django 4.2.23 on 2025-07-31 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsbriefingreport',
            name='user_profile_references',
            field=models.TextField(blank=True, null=True, verbose_name='User Profile References'),
        ),
    ]
