# Generated by Django 5.2 on 2025-06-10 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['-published_at']},
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='categories',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
